"""Wire contracts of the conversation routes + the SSE event vocabulary.

SSE events (schemas of the `data:` payloads): conversation · message · delta ·
tool_round · citations · grounding · done · error — conversation only on a
lazily created dialogue, citations/grounding only after a grounded turn,
error only instead of done (the HTTP status is already 200 mid-stream).
"""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from achilles.api.serialization import UtcDateTime
from achilles.query_engine.constants import MAX_MESSAGE_CHARS, TITLE_MAX_CHARS

# --- Requests ---


class MessageIn(BaseModel):
    # Strip like the rename field: a whitespace-only turn collapses to "" and is
    # rejected by min_length rather than opening a blank, empty-titled dialogue.
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    content: str = Field(min_length=1, max_length=MAX_MESSAGE_CHARS)
    # Sticky intent: switches conversations.selected_model when present;
    # validated against the chat_models allow-list.
    model: str | None = None


class ConversationRenameIn(BaseModel):
    # Same ceiling as the autogenerated label — one title budget everywhere.
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    title: str = Field(min_length=1, max_length=TITLE_MAX_CHARS)


class FeedbackIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: Literal[-1, 1] | None  # null clears the vote


class AccessIn(BaseModel):
    # The click on a source card — the second demand signal alongside citation
    # (retrieval.html#access-signal). One cited KS entity per click.
    model_config = ConfigDict(extra="forbid")

    entity_id: int = Field(gt=0)


# --- Responses ---


class CitationOut(BaseModel):
    marker: int  # the [n] the model used
    entity_id: int
    chunk_id: int | None = None
    title: str | None = None
    url: str | None = None
    source_type: str
    snippet: str | None = None  # the best fragment — record-level evidence


class GroundingOut(BaseModel):
    mode: Literal["grounded", "conversational"]
    outcome: Literal["found", "empty", "acl_hidden"] | None = None  # grounded only
    hidden_source_type: str | None = None  # acl_hidden coordinates, content-free
    hidden_author_email: str | None = None


class MessageOut(BaseModel):
    id: int
    role: str
    content: str
    model: str | None = None
    tokens_used: int | None = None
    feedback: int | None = None
    created_at: UtcDateTime
    citations: list[CitationOut] | None = None  # replayed with the same [n]
    # Terminal outcome of an assistant turn (NULL = completed); error_code
    # carries the reason on 'failed' — the replay redraws the same notice.
    finish: str | None = None
    error_code: str | None = None


class ConversationListItemOut(BaseModel):
    """One sidebar row; last_activity_at falls back to created_at when empty."""

    id: int
    title: str | None = None
    created_at: UtcDateTime
    last_activity_at: UtcDateTime


class ConversationOut(BaseModel):
    id: int
    title: str | None = None
    selected_model: str | None = None
    created_at: UtcDateTime
    messages: list[MessageOut]


class ChatModelOut(BaseModel):
    model_id: str  # the wire identity: messages.model / selected_model use it too
    display_name: str
    is_default: bool


class ChatModelsOut(BaseModel):
    items: list[ChatModelOut]
    # The user's personal sticky pick, seeding a fresh composer ahead of the
    # admin default. NULL, or a value no longer in `items`, → the picker falls
    # back to is_default (the same order the server resolves a turn in).
    selected: str | None = None


# --- SSE payloads ---


class ConversationEvent(BaseModel):
    id: int


class MessageEvent(BaseModel):
    user_message_id: int
    model: str


class DeltaEvent(BaseModel):
    text: str


class ToolRoundEvent(BaseModel):
    tools: list[str]  # names only — enough for a "searching…" state


class CitationsEvent(BaseModel):
    items: list[CitationOut]


class DoneEvent(BaseModel):
    assistant_message_id: int
    tokens_used: int | None = None


class ErrorEvent(BaseModel):
    code: str
    detail: str = ""
